version: "2"

services:
  db:
      image: postgres
      environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: mydbuser
          POSTGRES_PASSWORD: mydbpwd
      ports:
          - "5432:5432"
  backend:
    build: .
    command: bash -c "cd migrations; goose postgres "host=db user=mydbuser password=mydbpwd dbname=postgres sslmode=disable" up; cd .."
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - db
    environment:
      - DB_USER=mydbuser
      - DB_PASS=mydbpwd
    ports:
      - "80:80"
